version: "3.9"
services:
  rallyhost:
    build:
      context: ../
      dockerfile: ./test_scripts/redhat/Dockerfile
    image: couchbase/redhat
    hostname: 'clusterhost'
    tty: true
    ports: 
      - "8080:8091"
    networks:
      - cb-net-redhat
    container_name: redhat-clusterhost
    command: --version 6.6.1 -u couchbase -p foo123! -ch clusterhost -d -os RHEL -r -w 3 --services data,index,query -dm 256 -im 256 -qm 256
    privileged: true
  nodeone:
    image: couchbase/redhat
    hostname: 'node_one'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-redhat
    ports: 
      - "8081:8091"
    container_name: redhat-node-one
    command: --version 6.6.1 -u couchbase -p foo123! -ch redhat-clusterhost -d -os RHEL -r --services data,index,query -dm 256 -im 256 -qm 256
    privileged: true
  nodetwo:
    image: couchbase/redhat
    hostname: 'node_two'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-redhat
    ports: 
      - "8082:8091"
    container_name: redhat-node-two
    command: --version 6.6.1 -u couchbase -p foo123! -ch redhat-clusterhost -d -os RHEL -r --services data,index,query,analytics,eventing,fts -dm 256 -im 256 -qm 256 -am 1024 -em 256 -sm 256
    privileged: true
  nocluster:
    image: couchbase/redhat
    hostname: 'no_cluster'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-redhat
    ports: 
      - "8083:8091"
    container_name: redhat-no-cluster
    command: --version 6.6.1 -u couchbase -p foo123! -ch redhat-clusterhost -d -os RHEL -r --no-cluster --services data,index,query,analytics,eventing,fts -dm 256 -im 256 -qm 256 -am 1024 -em 256 -sm 256
    privileged: true
  gateway:
    image: couchbase/redhat
    hostname: 'gateway'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-redhat
    ports: 
      - "8085:4985"
      - "8086:4984"
    container_name: gateway
    command: --version 2.8.2 -u couchbase -p foo123! -ch redhat-clusterhost -d -os RHEL -g -r
    privileged: true      
networks:
  cb-net-redhat: