version: "3.3"
services:
  rallyhost:
    build:
      context: ../
      dockerfile: ./test_scripts/ubuntu/Dockerfile
    image: couchbase/ubuntu
    hostname: 'clusterhost'
    tty: true
    ports: 
      - "8080:8091"
    networks:
      - cb-net-ubuntu
    container_name: ubuntu-clusterhost
    command: --version 6.6.1 -u couchbase -p foo123! -ch clusterhost -d -os UBUNTU -r -w 3 --services data,index,query -dm 256 -im 256 -qm 256
    privileged: true
  nodeone:
    image: couchbase/ubuntu
    hostname: 'node_one'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-ubuntu
    ports: 
      - "8081:8091"
    container_name: ubuntu-node-one
    command: --version 6.6.1 -u couchbase -p foo123! -ch ubuntu-clusterhost -d -os UBUNTU -r --services data,index,query -dm 256 -im 256 -qm 256
    privileged: true   
  gateway:
    image: couchbase/ubuntu
    hostname: 'gateway'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-ubuntu
    ports: 
      - "8085:4985"
      - "8086:4984"
    container_name: gateway
    command: --version 2.8.2 -u couchbase -p foo123! -ch ubuntu-clusterhost -d -os UBUNTU -g -r
    privileged: true  
networks:
  cb-net-ubuntu: